Repository hibernate/hibernate-ogm, pull requests merged in 2018-05, with the labels that each got.

#1016 OGM-1465 Run test suite in alphabetical order
  pom.xml
Labels: +1 just push it!

#1017 OGM-1471 Check Transaction status for Rollback
  core/src/test/java/org/hibernate/ogm/backendtck/compensation/CompensationSpiTest.java
  core/src/test/java/org/hibernate/ogm/backendtck/queries/CompositeIdQueriesTest.java
  core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedCollectionTest.java
  core/src/test/java/org/hibernate/ogm/backendtck/queries/QueriesWithEmbeddedTest.java
  core/src/test/java/org/hibernate/ogm/backendtck/queries/SimpleQueriesWithTablePerClassNotSupportedTest.java
  core/src/test/java/org/hibernate/ogm/utils/OgmTestCase.java
Labels: Changes required

#1018 OGM-1461 Avoid RemoteHotRodServerRule to corrupt Maven's STDOUT by di…
  infinispan-remote/src/test/java/org/hibernate/ogm/datastore/infinispanremote/utils/RemoteHotRodServerRule.java
Labels: Ready for review
